### ISSUE TITLE
Misc touch issues

### ISSUE THREAD

**Issue by yol** [pkerling/xbmc#43]
After testing with a real touch screen, it seems that touch support is generally a little flaky in Kodi at the moment:

- Generic gesture detection does not handle > 2 touch points for tapping, but there are default action bindings that use it
- Press and hold sometimes does not seem to work (try picture viewer)
- Often controls get selected but don't register the press, i.e. there is no action
- Mouse cursor is being displayed on touch - weird on systems like Wayland where touch is not a pointer and thus does not move the Kodi cursor. Would be better to hide it during touches.

I was able to reproduce most issues on Android.

**Comment by fritsch** [comment]
You think it's fixable in a certain amount of time?

**Comment by yol** [comment]
Not sure, just documenting for now. It's not a priority, that's why I haven't assigned a milestone. The third point (controls not performing any action on press) is really annoying though, so I will probably look into that one.

**Comment by MartijnKaijser** [comment]
Told you it had some general issues :)

**Comment by yol** [comment]
Are there already trac tickets or something for reference?

**Comment by MartijnKaijser** [comment]
I'm sure there are but I certainly have nr 3 a lot on my tablet which stops me from using Kodi completely.

**Comment by yol** [comment]
Second and third point fixed by #12617 in upstream. Mouse can be disabled completely in options, (regarding fourth point) and first point is a general touch handler issue. There is no reason to keep the issue in this fork.
